name: Project Automations
on:
  issues:
    types:
      - opened
      - reopened
      - closed
      - labeled

env:
  new: 🆕 New
  in_review: 👀 In review
  done: ✅ Done
  gh_project_token: ${{ secrets.CANVAS_BOARD_TOKEN }}
  gh_organization: Workday
  gh_project_id: 4

jobs:
  issue_opened_or_reopened:
    name: issue_opened_or_reopened
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
    steps:
      - name: Move issue to ${{ env.new }}
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ env.gh_project_token }}
          organization: ${{ env.gh_organization }}
          project_id: ${{ env.gh_project_id }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.new }}
  issue_closed:
    name: issue_closed
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'closed'
    steps:
      - name: Moved issue to ${{ env.done }}
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ env.gh_project_token }}
          organization: ${{ env.gh_organization }}
          project_id: ${{ env.gh_project_id }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.done }}
  issue_labeled:
    name: issue_labeled
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'labeled'
    steps:
      - name: Add Issue Type - Bug
        if: github.event.label.name == 'bug'
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ env.gh_project_token }}
          organization: ${{ env.gh_organization }}
          project_id: ${{ env.gh_project_id }}
          resource_node_id: ${{ github.event.issue.node_id }}
          operation_mode: custom_field
          custom_field_values: '[{\"name\": \"Type\",\"type\": \"single_select\",\"value\": \"🐛 Bug\"}]'